# Generated by Django 4.2.5 on 2023-09-15 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garges', '0002_alter_garge_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Garge',
            new_name='Garage',
        ),
    ]
