# Generated by Django 4.2.6 on 2023-10-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('comedy', 'Comedy'), ('fantasy', 'Fantasy'), ('romance', 'Romance')], max_length=20),
        ),
    ]
